https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html#tutorial-setup

In [2]:
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']


In [4]:
from sklearn.datasets import fetch_20newsgroups

In [5]:
twenty_train = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)


In [6]:
twenty_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [7]:
len(twenty_train.data)

2257

In [8]:
len(twenty_train.filenames)

2257

In [9]:
print("\n".join(twenty_train.data[0].split("\n")[:3]))

From: sd345@city.ac.uk (Michael Collier)
Subject: Converting images to HP LaserJet III?
Nntp-Posting-Host: hampton


In [10]:
print(twenty_train.target_names[twenty_train.target[0]])

comp.graphics


In [11]:
for i in range(0,10):
    print(twenty_train.target_names[twenty_train.target[i]])

comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med


In [12]:
twenty_train.target

array([1, 1, 3, ..., 2, 2, 2], dtype=int64)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_counts.shape

(2257, 35788)

In [24]:
print ((2257*35788*2))

161547032


In [14]:
count_vect.vocabulary_.get(u'frequency')

14847

In [15]:
count_vect.vocabulary_.get(u'algorithm')

4690

In [16]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape
print(X_train_counts.toarra)

(2257, 35788)

In [20]:
corpus = [
    "This this that that that that the.",
    "that that that this this.",
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['that', 'the', 'this']
[[4 1 2]
 [3 0 2]]


In [25]:
vectorizer.inverse_transform(X)

[array(['the', 'that', 'this'], dtype='<U4'),
 array(['that', 'this'], dtype='<U4')]

In [39]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf = False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

(2257, 35788)

In [40]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, twenty_train.target)

NameError: name 'X_train_tfidf' is not defined

In [41]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tf, twenty_train.target)

In [42]:
docs_new = ['God is love', 'OpenGL on the GPU is fast']
X_new_counts = count_vect.transform(docs_new)
X_new_tfidf = tfidf_transformer.transform(X_new_counts)


predicted = clf.predict(X_new_tfidf)

for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, twenty_train.target_names[category]))



NameError: name 'tfidf_transformer' is not defined