In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.15.4


In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


create any array and find the memory occupied

In [6]:
Z = np.zeros((10,10))
print(Z.size, Z.itemsize, Z.size*Z.itemsize)

100 8 800


Print documentation of any function

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

Parameters
----------
start : scalar
    The starting value of the sequence.
stop : scalar
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dtype : dtype, optional
    The type of the ou

Create a null vector and set the 5 th element to 1

In [9]:
Z = np.zeros(10)
z[4] = 1
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49


In [10]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


reverse a vector


In [12]:
Z = np.arange(50)
Z = Z[::-1]

In [13]:
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [14]:
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [15]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
np.info(np.reshape)

 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options take no account of the me

In [17]:
import numpy as np
a = np.array([5,4])[np.newaxis]
print(a)
print(a.T)

[[5 4]]
[[5]
 [4]]


In [18]:
Z = np.arange(9).reshape(3,3)

In [19]:
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
nz = np.nonzero([1,2,0,0,4,0,])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [21]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.92819431 0.37656845 0.48262725]
  [0.40211102 0.84219955 0.99602215]
  [0.51745674 0.63300235 0.66634257]]

 [[0.12867309 0.06346286 0.17197454]
  [0.74793587 0.33592242 0.80437805]
  [0.53623481 0.56637377 0.99388736]]

 [[0.81441531 0.92343539 0.99488571]
  [0.24893015 0.3813956  0.83335826]
  [0.31569284 0.42014192 0.80887576]]]


In [23]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.02779587696512653 0.9962133684548161


In [25]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4457366932857762


In [26]:
x = np.ones((10,10))

In [28]:
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [29]:
x[1:-1,1:-1]=0

In [30]:
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
Z = np.array([0,1,2,3,4,5,6,7,8,9])
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
Y = np.array([0,0,1,1,0,0,1,1,1,0],dtype = 'bool')
Y

array([False, False,  True,  True, False, False,  True,  True,  True,
       False])

In [40]:
print(Z[Y])

[2 3 6 7 8]


In [41]:
print(Z[Z % 2 == 1])

[1 3 5 7 9]


In [42]:
Z [Z % 2 == 1]=0
print(Z)

[0 0 2 0 4 0 6 0 8 0]


In [56]:
A = np.array([12,32,45,67,556,34,56,789,33])
B = np.array([45,32,12,67,43,23,89,98,])
np.intersect1d(A,B)

array([12, 32, 45, 67])

In [57]:
def calc(a,b):
    return a*10+b
calc(178,59)

1839

In [52]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [59]:
print(Z[::-1])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [60]:
print(Z[::-1,::-1])

[[8 7 6]
 [5 4 3]
 [2 1 0]]


In [61]:
np.transpose(Z)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [62]:
import numpy as np
from scipy import signal, misc
import matplotlib.pyplot as plt

In [63]:
image = misc.face(gray=True).astype(np.float32)
derfilt = np.array([1.0, -2, 1.0], dtype=np.float32)
ck = signal.cspline2d(image, 8.0)
deriv = (signal.sepfir2d(ck, derfilt, [1]) +
        signal.sepfir2d(ck, [1], derfilt))

In [64]:
laplacian = np.array([[0,1,0], [1,-4,1], [0,1,0]], dtype=np.float32)
deriv2 = signal.convolve2d(ck,laplacian,mode='same',boundary='symm')

In [65]:
deriv

array([[ 2.4943466 ,  0.18423462, -2.4797058 , ...,  1.1341476 ,
        -0.94046783, -2.397995  ],
       [ 4.8883896 ,  2.5058823 , -0.33235168, ...,  0.9027405 ,
        -1.297226  , -2.785019  ],
       [ 6.3334427 ,  4.086052  ,  1.358017  , ...,  0.510025  ,
        -1.4734421 , -2.7400055 ],
       ...,
       [ 3.5466843 ,  2.648903  ,  1.0178452 , ..., -0.11502075,
         0.00747681,  0.16447449],
       [ 4.3137817 ,  2.9270782 ,  0.73696136, ...,  0.02685547,
         0.20732117,  0.39544678],
       [ 4.7405243 ,  3.1223907 ,  0.6977234 , ...,  0.21246338,
         0.43391418,  0.6474457 ]], dtype=float32)

In [73]:
Z = np.array([10,20,30,40,50], dtype = bool)


In [74]:
print(Z)

[ True  True  True  True  True]


In [77]:
np.full((3,3), False, dtype =bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [102]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [104]:
arr [arr %2 != 0]


array([1, 3, 5, 7, 9])

In [105]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr[arr%2 ==1]= -1

In [108]:
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [111]:
arr = np.arange(10)



In [113]:
res = np.where(arr%2 == 1, -1, arr)
print(arr)
print(res)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [1]:
D = {3.0:'HELLO'}

In [2]:
print(D)

{3.0: 'HELLO'}


In [6]:
# pi using the wallis formula
ep =1
for i in range(1,1000):
    t = 4*i*i
    r = t/(t-1)
    ep = r*ep
ep = 2 *ep
print(ep)

3.1408069608284657


In [7]:
ep =1
for i in range(1,1000000):
    t = 4*i*i
    r = t/(t-1)
    ep = r*ep
ep = 2 *ep
print(ep)

3.1415918681913633


In [ ]:
def func