In [4]:
import numpy as np

l= np.array(["2",3.0,4])
print(l)

['2' '3.0' '4']


In [5]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
np.thousands(5,dtype='int')

AttributeError: module 'numpy' has no attribute 'thousands'

In [7]:
np.twos(5,dtype='int')

AttributeError: module 'numpy' has no attribute 'twos'

In [9]:
np.full((3, 5), 10000000000)

array([[10000000000, 10000000000, 10000000000, 10000000000, 10000000000],
       [10000000000, 10000000000, 10000000000, 10000000000, 10000000000],
       [10000000000, 10000000000, 10000000000, 10000000000, 10000000000]],
      dtype=int64)

In [10]:
np.random.random((3, 3))

array([[0.37955253, 0.61524357, 0.546597  ],
       [0.88486129, 0.06313242, 0.61821052],
       [0.27882747, 0.47424238, 0.86411752]])

In [11]:
np.random.normal(0, 1, (3, 3))

array([[-0.5466369 ,  0.39553688, -1.29348376],
       [-0.95161098,  0.41886863, -0.75655572],
       [-0.78593201, -0.97398244,  0.26540971]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.beye(3)

AttributeError: module 'numpy' has no attribute 'beye'

In [14]:
np.empty(3)

array([1., 1., 1.])

In [15]:
np.zeros(10, dtype='int_')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
print("dtype:", x3.dtype)

NameError: name 'x3' is not defined

In [17]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)

NameError: name 'x3' is not defined

In [18]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [19]:
print("dtype:", x3.dtype)

dtype: int32


In [20]:
print("itemsize:", x3.itemsize, "bytes")

itemsize: 4 bytes


In [21]:
print("nbytes:", x3.nbytes, "bytes")


nbytes: 240 bytes


In [22]:
np.random.seed(0)
np.random.random(10)


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [23]:
x1

array([0, 3, 6, 6, 4, 6])

In [24]:
x1[0]=10


In [1]:
print(x2)


NameError: name 'x2' is not defined

In [2]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [3]:
b=a[2:4]
b

[3, 4]

In [4]:
b[0]=7
b

[7, 4]

In [5]:
a

[1, 2, 3, 4, 5]

In [6]:
import numpy as np
c= np.array([1,2,3,4,5])

In [7]:
c

array([1, 2, 3, 4, 5])

In [8]:
d=c[2:4]
d

array([3, 4])

In [9]:
d[0]=7
d

array([7, 4])

In [10]:
c

array([1, 2, 7, 4, 5])

In [11]:
e= c[2:4].copy()
e

array([7, 4])

In [12]:
c


array([1, 2, 7, 4, 5])

In [13]:
e[0]=3
e

array([3, 4])

In [14]:
c

array([1, 2, 7, 4, 5])

In [15]:
nidhi= np.arange([1,2,3,4,5,6])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [20]:
grid = np.arange(1, 10).reshape((2,3))
print(grid)

ValueError: cannot reshape array of size 9 into shape (2,3)

In [21]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
grid = np.arange(1, 10).reshape((9, 1))
print(grid)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [24]:
grid[,:]


SyntaxError: invalid syntax (<ipython-input-24-8f271ab1c086>, line 1)

In [25]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [26]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [28]:
x = np.array([1, 2, 3])
y = np.array([3, 2],[5,6])
np.concatenate([x, y])

TypeError: data type not understood

In [29]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [30]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.72 s ± 6.45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
%timeit (1.0 / big_array

SyntaxError: unexpected EOF while parsing (<unknown>, line 1)

In [32]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [33]:
%timeit (1.0 / big_array)

3.87 ms ± 26 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
np.arange(5) / np.arange(1, 6)


array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [36]:
y = np.zeros(10)
np.power(2, y, out=y[::2])
print(y)

ValueError: operands could not be broadcast together with shapes () (10,) (5,) 

In [37]:
x=np.arrange(5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [38]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [39]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [40]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [41]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [45]:
L = np.random.random(100)
sum(L)

48.92747670226663

In [46]:
import numpy as np
np.__version__


'1.15.4'

In [49]:
!head -4 president_height.csv

'head' is not recognized as an internal or external command,
operable program or batch file.


In [51]:
import pandas as pd
data = pd.read_csv('president_height.csv')
heights = np.array(data['height(cm)'])
print(heights)

EmptyDataError: No columns to parse from file